In [10]:
import numpy as np #행렬연산

In [2]:
m1 = np.array([0,1,2,3]).reshape(2,2)
m2 = np.array([3,2,1,0]).reshape(2,2)

In [3]:
m1.dot(m2)

array([[1, 0],
       [9, 4]])

In [4]:
np.dot(m1,m2)

array([[1, 0],
       [9, 4]])

In [5]:
m1.transpose()

array([[0, 2],
       [1, 3]])

In [6]:
np.transpose(m1)

array([[0, 2],
       [1, 3]])

In [7]:
np.linalg.inv(m1)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [8]:
np.linalg.det(m1)

-2.0