In [11]:
import numpy as np #배열의 인덱싱과 슬라이싱

In [13]:
arr_m = np.arange(10, 100, 10).reshape(3,3)

In [14]:
arr_m

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
# 선택 후 값 변경
arr_m[0,2]
arr_m[2,2]=95
arr_m

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [17]:
# 행전체 지정하여 행 전체 변경
arr_m[1]
arr_m[1] = np.array([45,55,65])
arr_m
arr_m[1] = [47,57,67]
arr_m

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [18]:
# 행과 열의 위치를 지정해 여러 원소 가져옴
arr_m[[0,2], [0,1]]

array([10, 80])