In [1]:
import numpy as np

In [2]:
np.random.rand()

0.9419502335190039

In [3]:
np.random.rand(2,3)

array([[0.39823919, 0.15800967, 0.113248  ],
       [0.40657335, 0.73159353, 0.02888129]])

In [4]:
np.random.rand(2,3,2)

array([[[0.08677075, 0.57790875],
        [0.68067808, 0.34660641],
        [0.93073196, 0.04386036]],

       [[0.90511341, 0.08011441],
        [0.95826508, 0.1908488 ],
        [0.27334433, 0.2609294 ]]])

In [5]:
np.random.randint(1,20)

16

In [7]:
np.random.randint(10, size=(3,3))

array([[6, 5, 6],
       [8, 5, 8],
       [7, 2, 9]])

In [10]:
num_arr1 = np.array([10,20,30])
num_arr2 = np.array([1,2,3])

In [11]:
num_arr1 + num_arr2

array([11, 22, 33])

In [12]:
num_arr1 - num_arr2

array([ 9, 18, 27])

In [13]:
num_arr1 * 2

array([20, 40, 60])

In [18]:
num_arr = np.arange(1,6)
num_arr

array([1, 2, 3, 4, 5])

In [22]:
[num_arr.sum(), num_arr.mean()]

[15, 3.0]

In [25]:
[num_arr1.cumsum(), num_arr1.cumprod()]

[array([10, 30, 60], dtype=int32), array([  10,  200, 6000], dtype=int32)]

In [24]:
num_arr1.cumsum()

array([10, 30, 60], dtype=int32)

In [26]:
m1 = np.array([0,1,2,3]).reshape(2,2)
m2 = np.array([3,2,1,0]).reshape(2,2)

In [27]:
m1.dot(m2)

array([[1, 0],
       [9, 4]])