In [15]:
import numpy as np

In [7]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [8]:
a1.dtype

dtype('int32')

In [10]:
data2=[0.5,2,0.01,8]
a2 = np.array(data2)
a2

array([0.5 , 2.  , 0.01, 8.  ])

In [11]:
a2.dtype

dtype('float64')

In [24]:
np.arange(0,10,2)
np.arange(1,10)
np.arange(3)

array([0, 1, 2])

In [25]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
m = np.arange(6).reshape(2,3)

In [28]:
m.shape

(2, 3)

In [30]:
np.linspace(1,5,10)
np.linspace(0,np.pi, 10) #numpyDML ㅠ

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [36]:
np.zeros(9).reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])