In [1]:
!pip install numpy as np

ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as


In [2]:
import numpy as np

In [ ]:
m1 = np.array([0,1,2,3]).reshape(2,2)
m2 = np.array([3,2,1,0]).reshape(2,2)

In [ ]:
m1.dot(m2)

array([[1, 0],
       [9, 4]])

In [ ]:
np.dot(m1,m2)

array([[1, 0],
       [9, 4]])

In [ ]:
m1.transpose()

array([[0, 2],
       [1, 3]])

In [ ]:
np.transpose(m1)

array([[0, 2],
       [1, 3]])

In [ ]:
np.linalg.inv(m1)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [ ]:
np.linalg.det(m1)

-2.0